export const workCases = [
  {
    title: "ExploraOne",
    category: "Web Development",
    description: `ExploraOne is a Filipino travel agency that offers affordable quality trips all over the world. The work I do for this site consists of helping them building/maintaining their Site with multiple language layers.`,
    caseBackground: "/images/tablet-background.webp",
    caseImage: "/images/explora-case-tablet.webp",
    caseImageMobile: "/images/explora-project-mobile.webp",
    caseImageAlt: "ExploraONE website case by John Empuerto",
    caseLink: "https://exploraone.com",
    caseLinkText: "Visit site",
  },
  {
    title: "Todo List",
    category: "Web Application",
    description: "A Simple To-Do List app built with React.js",
    caseBackground: "/images/lunar-background.webp",
    caseImage: null,
    caseImageOne: "/images/todo-first.webp",
    caseImageTwo: "/images/todo-second.webp",
    caseImageMobile: "/images/todo-project-mobile.webp",
    caseImageAlt: "Todo-list by John Empuerto",
    caseLink: "#",
    caseLinkText: "Visit site",
  },
  {
    title: "Nordsjælland Osteopati & Fysioterapi",
    category: "WordPress Website",
    description: "Nordsjælland Osteopati & Fysioterapi consists of Jakob Aagaard, who does osteopathic and physiotherapeutic treatments at his clinic in Farum, Denmark. His needs were a WordPress website for information and booking, which was built with Elementor.",
    caseBackground: "/images/tablet-background.webp",
    caseImage: "/images/nordsjaelland-osteopati-case-tablet.webp",
    caseImageMobile: "/images/nordsjaelland-osteopati-project-mobile.webp",
    caseImageAlt: "nordsjaelland osteopati og fysioterapi wordpress website by John Empuerto",
    caseLink: "https://nordsjaelland-osteopati.dk/",
    caseLinkText: "Visit site",
  },
  {
    title: "Github Search Users",
    category: "Web Application",
    description: "A nicer look at your GitHub profile and repository stats with data visualizations of your top languages and stars. Sort through your top repos by number of stars, forks, and size.",
    caseBackground: "/images/tablet-background.webp",
    caseImage: "/images/github-case-tablet.webp",
    caseImageMobile: "/images/github-project-mobile.webp",
    caseImageAlt: "github user search  by John Empuerto",
    caseLink: "https://githubusersearchreact.netlify.app/",
    caseLinkText: "Visit site",
  },
  {
    title: "Personal Website V1",
    category: "WordPress Website",
    description: "My first personal website built with HTML, CSS, Javascript and hosted on GitHub Pages.",
    caseBackground: "/images/tablet-background.webp",
    caseImage: "/images/johnempuerto-case-tablet.webp",
    caseImageMobile: "/images/johnempuerto-project-mobile.webp",
    caseImageAlt: "Personal Website by John Empuerto",
    caseLink: "https://jaanreymond.github.io/johnempuertoo/",
    caseLinkText: "Visit site",
  },
  
  
]

export default workCases;